INSERT INTO public.app_region (id, nombre) VALUES (1, 'Región de Tarapaca');
INSERT INTO public.app_region (id, nombre) VALUES (2, 'Región de Antofagasta');
INSERT INTO public.app_region (id, nombre) VALUES (3, 'Región de Atacama');
INSERT INTO public.app_region (id, nombre) VALUES (4, 'Región de Coquimbo');
INSERT INTO public.app_region (id, nombre) VALUES (5, 'Región de Valparaíso');
INSERT INTO public.app_region (id, nombre) VALUES (6, 'Región del Libertador Bernardo Ohiggins');
INSERT INTO public.app_region (id, nombre) VALUES (7, 'Región del Maule');
INSERT INTO public.app_region (id, nombre) VALUES (8, 'Región del Bío-Bío');
INSERT INTO public.app_region (id, nombre) VALUES (9, 'Región de la Araucanía');
INSERT INTO public.app_region (id, nombre) VALUES (10, 'Región de los Lagos');
INSERT INTO public.app_region (id, nombre) VALUES (11, 'Región Aisén del General Carlos Ibáñez del Campo');
INSERT INTO public.app_region (id, nombre) VALUES (12, 'Región de Magallanes y la Antártica Chilena');
INSERT INTO public.app_region (id, nombre) VALUES (13, 'Región Metropolitana de Santiago');
INSERT INTO public.app_region (id, nombre) VALUES (14, 'Región de los Rios');
INSERT INTO public.app_region (id, nombre) VALUES (15, 'Región Arica y Parinacota');